Imports System.Net.Mail
Imports System.Data.SqlClient

Public Class PurchaseAdmin
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Session("Username") = Me.User.Identity.Name.ToString
        Session("DateOrderEntry") = Now()
    End Sub

    Protected Sub frmView_ItemUpdated(sender As Object, e As FormViewUpdatedEventArgs)
        'Dim body As String = "This Email was automatically generated by the purchase request tool!" & vbCrLf & _
        '             "Item: " & CType(frmView.FindControl("ItemNameTextbox"), Label).Text & vbCrLf & _
        '             "Description: " & CType(frmView.FindControl("DescriptionTextBox"), TextBox).Text & vbCrLf & _
        '             "Reason: " & CType(frmView.FindControl("ReasonTextBox"), TextBox).Text & vbCrLf & _
        '             "Quantity: " & CType(frmView.FindControl("QuantityTextBox"), Label).Text & vbCrLf & _
        '             "Cost not to exceed: " & CType(frmView.FindControl("TotalPriceTextBox"), Label).Text & vbCrLf & _
        '             "Date Required: " & CType(frmView.FindControl("DateRequiredTextBox"), Label).Text & vbCrLf & _
        '             "Requested by: " & CType(frmView.FindControl("RequesterNameTextBox"), Label).Text & vbCrLf & _
        '             "Approved by: " & CType(frmView.FindControl("ManagerIDTextBox"), Label).Text & vbCrLf & _
        '             "Approved on: " & CType(frmView.FindControl("ManagerApprovalDateTextBox"), Label).Text & vbCrLf & _
        '             "Buyer: " & CType(frmView.FindControl("BuyerNameTextBox"), Label).Text & vbCrLf & _
        '             "Date entered: " & Session("DateOrderEntry") & vbCrLf & _
        '             "PO: " & CType(frmView.FindControl("LCLPurchaseOrderTextBox"), TextBox).Text

        'Dim mm As New MailMessage("ddnguyen@laurentide.com", CType(frmView.FindControl("RequesterEmailTextBox"), Label).Text, "Order Entered (ID: " & CType(frmView.FindControl("PurchaseRequestIDLabel1"), Label).Text & ")", body)
        ''mm.CC.Add("support@laurentide.com")
        'Dim smtp As New SmtpClient("lcl-exc")
        'smtp.Send(mm)
        'Refresh Gridview
        gvPurchaseRequests.DataBind()
    End Sub
End Class