'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Safety

    '''<summary>
    '''ScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''frmInsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmInsert As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''gvSafetyCases control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSafetyCases As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''sdsInsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsInsert As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsSafetyCasesGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsSafetyCasesGrid As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsSafetyCauses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsSafetyCauses As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsStatus As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsSafetyTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsSafetyTypes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsManagers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsManagers As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsSaLTMembers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsSaLTMembers As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsProvinces control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsProvinces As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsLesions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsLesions As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsTreatments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsTreatments As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsDepartments As Global.System.Web.UI.WebControls.SqlDataSource
End Class
