Imports System.Net.Mail
Imports System.Data.SqlClient

Public Class PurchaseManager
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Session("Username") = Me.User.Identity.Name.ToString
        Session("DateApproved") = Now()
    End Sub

    Protected Sub frmView_ItemUpdated(sender As Object, e As FormViewUpdatedEventArgs)
        'Send Email back to user telling him that his request was approved if it was
        If CType(frmView.FindControl("ApprovedCheckBox"), CheckBox).Checked Then
            Dim body As String = "This Email was automatically generated by the purchase request tool!" & vbCrLf & _
                                 "Item: " & CType(frmView.FindControl("ItemNameTextbox"), Label).Text & vbCrLf & _
                                 "Description: " & CType(frmView.FindControl("DescriptionTextBox"), TextBox).Text & vbCrLf & _
                                 "Reason: " & CType(frmView.FindControl("ReasonTextBox"), TextBox).Text & vbCrLf & _
                                 "Quantity: " & CType(frmView.FindControl("QuantityTextBox"), Label).Text & vbCrLf & _
                                 "Cost not to exceed: " & CType(frmView.FindControl("TotalPriceTextBox"), Label).Text & vbCrLf & _
                                 "Date Required: " & CType(frmView.FindControl("DateRequiredTextBox"), Label).Text & vbCrLf & _
                                 "Requested by: " & CType(frmView.FindControl("RequesterNameTextBox"), Label).Text & vbCrLf & _
                                 "Approved by: " & CType(frmView.FindControl("ManagerIDTextBox"), TextBox).Text & vbCrLf & _
                                 "Approved on: " & CType(frmView.FindControl("ManagerApprovalDateTextBox"), Label).Text
            If CType(frmView.FindControl("ITReviewCheckBox"), CheckBox).Checked Then
                body = body & vbCrLf & "Message to IT: " & CType(frmView.FindControl("ITMessageTextBox"), TextBox).Text
            end if
            Dim mm As New MailMessage("ddnguyen@laurentide.com", CType(frmView.FindControl("RequesterEmailTextBox"), Label).Text, "Request Approved (ID: " & CType(frmView.FindControl("PurchaseRequestIDLabel1"), Label).Text & ")", body)
            If CType(frmView.FindControl("ITReviewCheckBox"), CheckBox).Checked Then
                mm.CC.Add("support@laurentide.com")
            End If
            Dim smtp As New SmtpClient("lcl-exc")
            smtp.Send(mm)
        End If
        'Refresh Gridview
        gvPurchaseRequests.DataBind()
    End Sub
End Class