'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PurchaseManager

    '''<summary>
    '''ScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''frmView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmView As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''gvPurchaseRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPurchaseRequests As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''sdsUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsUpdate As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsPurchaseRequestsGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsPurchaseRequestsGrid As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsManagers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsManagers As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsDepartments As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsApprovalTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsApprovalTypes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsBuyers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsBuyers As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsStatuses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsStatuses As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsPurchaseCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsPurchaseCategories As Global.System.Web.UI.WebControls.SqlDataSource
End Class
