'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Customer_Management

    '''<summary>
    '''gvQB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvQB As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''sdsQuotebuilder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsQuotebuilder As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsAE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsAE As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsCSR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCSR As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsOS As Global.System.Web.UI.WebControls.SqlDataSource
End Class
